# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("Version of numpy:", np.__version__)
print("Numpy configuration:")
np.show_config()

Version of numpy: 1.26.4
Numpy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a=np.random.random((2,3,5))


a=np.random.randint(5, size=(2,3,5))


a=np.random.uniform(10,20, size=(2,3,5))



### 4. Print a.


In [4]:
### [your code here]
print(a)

[[[17.1514814  15.3183518  11.79877833 14.34229559 15.95530138]
  [14.23996941 17.56005012 11.86001808 19.49609448 11.93074439]
  [15.5196677  15.90555901 13.18650157 16.22285247 11.04208847]]

 [[16.31190519 17.91421148 11.85726383 17.17026387 13.88574373]
  [15.92888014 16.25947065 11.40107665 10.23259322 16.14151084]
  [16.70010902 13.18277641 17.24522569 15.89551818 13.51780244]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
np.size(a) == np.size(b)

True


### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
try:
    a+b
except ValueError as e:
    print(f"Due to different array shapes, the operation is not possible.\n",e)

Due to different array shapes, the operation is not possible.
 operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
c=np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [19]:
### [your code here]
d=a+c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
### [your code here]
print("a:\n",a)
print("d:\n",d)

#each element in a is incremented by 1 so now d is equal to a+1.

a:
 [[[17.1514814  15.3183518  11.79877833 14.34229559 15.95530138]
  [14.23996941 17.56005012 11.86001808 19.49609448 11.93074439]
  [15.5196677  15.90555901 13.18650157 16.22285247 11.04208847]]

 [[16.31190519 17.91421148 11.85726383 17.17026387 13.88574373]
  [15.92888014 16.25947065 11.40107665 10.23259322 16.14151084]
  [16.70010902 13.18277641 17.24522569 15.89551818 13.51780244]]]
d:
 [[[18.1514814  16.3183518  12.79877833 15.34229559 16.95530138]
  [15.23996941 18.56005012 12.86001808 20.49609448 12.93074439]
  [16.5196677  16.90555901 14.18650157 17.22285247 12.04208847]]

 [[17.31190519 18.91421148 12.85726383 18.17026387 14.88574373]
  [16.92888014 17.25947065 12.40107665 11.23259322 17.14151084]
  [17.70010902 14.18277641 18.24522569 16.89551818 14.51780244]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
### [your code here]
e=a*c
e

array([[[17.1514814 , 15.3183518 , 11.79877833, 14.34229559,
         15.95530138],
        [14.23996941, 17.56005012, 11.86001808, 19.49609448,
         11.93074439],
        [15.5196677 , 15.90555901, 13.18650157, 16.22285247,
         11.04208847]],

       [[16.31190519, 17.91421148, 11.85726383, 17.17026387,
         13.88574373],
        [15.92888014, 16.25947065, 11.40107665, 10.23259322,
         16.14151084],
        [16.70010902, 13.18277641, 17.24522569, 15.89551818,
         13.51780244]]])



### 13. Does e equal to a? Why or why not?


In [13]:
### [your code here]
are_equal=np.array_equal(a,e)

print(are_equal)   # Because the elements in the array c were all 1.

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]

d_max=np.max(d)
print(d_max)

d_min=np.min(d)
print(d_min)

d_mean=np.mean(d)
print(d_mean)


20.496094478201474
11.232593221254579
15.83913685160204



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f=np.empty((2,3,5))
print(f)

[[[17.1514814  15.3183518  11.79877833 14.34229559 15.95530138]
  [14.23996941 17.56005012 11.86001808 19.49609448 11.93074439]
  [15.5196677  15.90555901 13.18650157 16.22285247 11.04208847]]

 [[16.31190519 17.91421148 11.85726383 17.17026387 13.88574373]
  [15.92888014 16.25947065 11.40107665 10.23259322 16.14151084]
  [16.70010902 13.18277641 17.24522569 15.89551818 13.51780244]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
### [your code here]
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75 
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)


[[[ 75.  75.  25.  25.  75.]
  [ 25.  75.  25. 100.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.   0.  75.]
  [ 75.  25.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
### [your code here]
print(d)
print(f)

[[[18.1514814  16.3183518  12.79877833 15.34229559 16.95530138]
  [15.23996941 18.56005012 12.86001808 20.49609448 12.93074439]
  [16.5196677  16.90555901 14.18650157 17.22285247 12.04208847]]

 [[17.31190519 18.91421148 12.85726383 18.17026387 14.88574373]
  [16.92888014 17.25947065 12.40107665 11.23259322 17.14151084]
  [17.70010902 14.18277641 18.24522569 16.89551818 14.51780244]]]
[[[ 75.  75.  25.  25.  75.]
  [ 25.  75.  25. 100.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.   0.  75.]
  [ 75.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [18]:
### [your code here]

f[(d > d_min) & (d < d_mean)] = 'B'
f[(d > d_mean) & (d < d_max)] = 'D'
f[d == d_mean] = 'C'
f[d == d_min] = 'A'
f[d == d_max] = 'E'

print(f)

ValueError: could not convert string to float: 'B'